---
name: dotfiles-zsh-modular
description: "Modular Zsh: numbered sourcing, Zinit, encrypted secrets."
version: 1.0.0
author: Hermes Agent
license: MIT
platforms: [linux, macos, windows]
metadata:
  hermes:
    tags: [dotfiles, zsh, modular, zinit, starship, encrypted]
    category: devops
requires_toolsets: [terminal, file]
supersedes: []
---

# Dotfiles Zsh Modular Skill

**Trigger**: Use when designing or debugging modular Zsh configurations — numbered module sourcing, Zinit plugin management, Starship prompt, encrypted secrets loading, workplace-specific configs.

**Goal**: Provide complete reference for Zsh modular patterns from `fabiosouzadev/dotfiles` enabling maintainable, profile-aware shell configuration.

---

## 1. Architecture Overview

### Module Structure

```
home/
├── dot_zshrc.tmpl              # Main entry point (sources modules)
├── dot_zshrc.d/                # Module directory (numbered 099-999)
│   ├── 099-environment.zsh     # Environment variables (FIRST)
│   ├── 100-zinit.zsh           # Zinit plugin manager
│   ├── 110-omz.zsh             # Oh My Zsh libs
│   ├── 120-plugins.zsh         # Zsh plugins (fzf, zoxide, atuin, etc.)
│   ├── 130-history.zsh         # History config
│   ├── 140-completion.zsh      # Completion system
│   ├── 150-keybindings.zsh     # Key bindings
│   ├── 160-aliases.zsh         # Common aliases
│   ├── 170-functions.zsh       # Custom functions
│   ├── 180-tools.zsh           # Tool integrations (mise, docker, etc.)
│   ├── 190-vi-mode.zsh         # Vi mode config
│   ├── 200-workplace.zsh       # Workplace detection (Zup)
│   ├── 210-personal.zsh        # Personal laptop config
│   ├── 220-vps.zsh             # VPS config
│   ├── 300-ai-tools.zsh        # AI tools (aider, claude, etc.)
│   ├── 310-hermes.zsh          # Hermes integration
│   ├── 320-omniroute.zsh       # OmniRoute integration
│   ├── 330-coding-orchestrator.zsh  # Coding Orchestrator
│   ├── 999-compinit.zsh        # Compinit (LAST)
└── private_dot_config/
    ├── encrypted_api_keys.zsh.asc    # GPG-encrypted secrets
    ├── encrypted_ssh_config.zsh.asc
    └── encrypted_workplace.zsh.asc
```

### Sourcing Order (Critical)

```
1. 099-environment.zsh      → Env vars MUST be first (PATH, EDITOR, etc.)
2. 100-199: Core shell      → Zinit, plugins, history, completion, keys
3. 200-299: Profile-specific → Workplace, personal, VPS overrides
4. 300-399: AI integrations → Hermes, OmniRoute, Orchestrator
5. 999-compinit.zsh         → Compinit MUST be last
```

---

## 2. Main Entry Point (`dot_zshrc.tmpl`)

```go
# {{ .chezmoi.sourceFile }} - Modular Zsh Configuration
# Profile: {{ .settings.profile }}
# Generated by chezmoi - DO NOT EDIT DIRECTLY

# ===== EARLY ENVIRONMENT (before anything else) =====
{{- $envFiles := list
  "099-environment.zsh"
-}}
{{- range $envFiles }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/{{ . }}"
{{- end }}

# ===== ZINIT & PLUGINS (must be early) =====
source "{{ .chezmoi.homeDir }}/.zshrc.d/100-zinit.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/110-omz.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/120-plugins.zsh"

# ===== CORE SHELL CONFIG =====
source "{{ .chezmoi.homeDir }}/.zshrc.d/130-history.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/140-completion.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/150-keybindings.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/160-aliases.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/170-functions.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/180-tools.zsh"
source "{{ .chezmoi.homeDir }}/.zshrc.d/190-vi-mode.zsh"

# ===== PROFILE-SPECIFIC (conditional) =====
{{- if .features.workplace.zup }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/200-workplace.zsh"
{{- else if eq .settings.profile "personal" }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/210-personal.zsh"
{{- else if eq .settings.profile "vps" }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/220-vps.zsh"
{{- end }}

# ===== AI INTEGRATIONS =====
{{- if .features.ai.coding_assistants }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/300-ai-tools.zsh"
{{- end }}
{{- if .features.ai.hermes.dashboard.enabled }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/310-hermes.zsh"
{{- end }}
{{- if .features.ai.omniroute.enabled }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/320-omniroute.zsh"
{{- end }}
{{- if .features.ai.coding_orchestrator.enabled }}
source "{{ .chezmoi.homeDir }}/.zshrc.d/330-coding-orchestrator.zsh"
{{- end }}

# ===== ENCRYPTED SECRETS (GPG) =====
{{- if .features.secrets.gpg }}
{{- $secretFiles := list
  "encrypted_api_keys.zsh.asc"
  "encrypted_ssh_config.zsh.asc"
  "encrypted_workplace.zsh.asc"
-}}
{{- range $secretFiles }}
{{- $decrypted := (printf "%s/.config/%s" .chezmoi.homeDir .) | replace ".asc" "" }}
# Decrypt and source {{ . }}
if [[ -f "{{ .chezmoi.homeDir }}/.config/{{ . }}" ]]; then
  source <(gpg --quiet --decrypt "{{ .chezmoi.homeDir }}/.config/{{ . }}" 2>/dev/null)
fi
{{- end }}
{{- end }}

# ===== COMPINIT (MUST BE LAST) =====
source "{{ .chezmoi.homeDir }}/.zshrc.d/999-compinit.zsh"

# ===== STARSHIP PROMPT (after compinit) =====
{{- if .features.prompt.starship }}
eval "$(starship init zsh)"
{{- end }}
```

---

## 3. Key Module Examples

### 099-environment.zsh (FIRST - PATH, EDITOR, etc.)

```zsh
# Environment Variables
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
export LESS="-R"

# XDG Base Directories
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# Local bin directories (mise, chezmoi scripts, etc.)
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.go/bin:$PATH"

# Language-specific
export GOENV_ROOT="$HOME/.goenv"
export PYENV_ROOT="$HOME/.pyenv"
export NODE_ENV="${NODE_ENV:-development}"

# GPG
export GPG_TTY=$(tty)

# FZF
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"

# Atuin
export ATUIN_SESSION=$(atuin uuid 2>/dev/null || echo "default")

# Mise (runtime version manager)
export MISE_DATA_DIR="$HOME/.local/share/mise"
export MISE_CONFIG_DIR="$HOME/.config/mise"
```

### 100-zinit.zsh (Plugin Manager)

```zsh
# Zinit Installation & Setup
ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
if [[ ! -f "$ZINIT_HOME/zinit.zsh" ]]; then
  mkdir -p "$(dirname "$ZINIT_HOME")"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "$ZINIT_HOME/zinit.zsh"

# Zinit Annexes
zinit light-mode for \
  zdharma-continuum/zinit-annex-as-monitor \
  zdharma-continuum/zinit-annex-bin-gem-node \
  zdharma-continuum/zinit-annex-patch-dl \
  zdharma-continuum/zinit-annex-rust
```

### 120-plugins.zsh (Essential Plugins)

```zsh
# ===== COMPLETION =====
zinit light zsh-users/zsh-completions
zinit light Aloxaf/fzf-tab

# ===== SYNTAX HIGHLIGHTING =====
zinit light zdharma-continuum/fast-syntax-highlighting

# ===== AUTOSUGGESTIONS =====
zinit light zsh-users/zsh-autosuggestions

# ===== HISTORY SUBSTRING SEARCH =====
zinit light zsh-users/zsh-history-substring-search

# ===== DIRECTORY NAVIGATION =====
zinit light ajeetdsouza/zoxide

# ===== ATUIN (Shell History) =====
zinit ice wait'1' lucid
zinit light atuinsh/atuin

# ===== OH MY ZSH LIBS =====
zinit snippet OMZL::git.zsh
zinit snippet OMZL::directories.zsh
zinit snippet OMZL::functions.zsh
zinit snippet OMZL::grep.zsh
zinit snippet OMZL::history.zsh
zinit snippet OMZL::key-bindings.zsh
zinit snippet OMZL::spectrum.zsh
zinit snippet OMZL::termsupport.zsh

# ===== OH MY ZSH PLUGINS =====
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::command-not-found
zinit snippet OMZP::colored-man-pages
zinit snippet OMZP::extract
zinit snippet OMZP::docker
zinit snippet OMZP::docker-compose
zinit snippet OMZP::kubectl
```

### 200-workplace.zsh (Zup Workplace)

```zsh
# Zup Workplace Configuration
# Only loaded when .features.workplace.zup = true

# Git config for work
export GIT_AUTHOR_EMAIL="fabio.vanderlei@zup.com.br"
export GIT_COMMITTER_EMAIL="fabio.vanderlei@zup.com.br"
git config --global user.email "fabio.vanderlei@zup.com.br"

# SSH key for work GitHub
export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_ed25519_work -o IdentitiesOnly=yes'

# VPN helper
zup-vpn() {
  if [[ -f ~/.config/instivo/config.ovpn ]]; then
    sudo openvpn --config ~/.config/instivo/config.ovpn
  else
    echo "Instivo VPN config not found"
  fi
}

# Bob (Zup internal tool)
if command -v bob &>/dev/null; then
  alias zup-deploy="bob deploy"
  alias zup-logs="bob logs --tail=100"
  alias zup-shell="bob shell"
fi

# AWS Profile
export AWS_PROFILE="${AWS_PROFILE:-zup-prod}"

# Kubernetes context
alias kctx-zup="kubectl config use-context zup-cluster"
```

### 220-vps.zsh (VPS Specific)

```zsh
# VPS Configuration
# Only loaded when .settings.profile = "vps"

# No GUI, minimal aliases
alias ls="ls --color=auto"
alias ll="ls -la"
alias la="ls -A"

# Docker (via Dockge)
alias dk="docker"
alias dkc="docker compose"
alias dkl="docker logs -f"

# Tailscale
alias ts="tailscale"
alias tsup="tailscale up"
alias tsdown="tailscale down"

# Caddy
alias caddy-reload="sudo caddy reload --config /etc/caddy/Caddyfile"
alias caddy-logs="sudo journalctl -u caddy -f"

# Systemd
alias sc="sudo systemctl"
alias sc-status="sudo systemctl status"
alias sc-logs="sudo journalctl -u"

# Hermes/OmniRoute (running as services)
alias hermes-logs="sudo journalctl -u hermes -f"
alias omniroute-logs="sudo journalctl -u omniroute -f"
alias orchestrator-logs="sudo journalctl -u coding-orchestrator -f"
```

### 300-ai-tools.zsh (AI Coding Assistants)

```zsh
# AI Tools Configuration
# Only loaded when .features.ai.coding_assistants = true

# Aider
export AIDER_MODEL="${AIDER_MODEL:-claude-3-5-sonnet-20241022}"
export AIDER_WEAK_MODEL="${AIDER_WEAK_MODEL:-claude-3-haiku-20240307}"
alias aider-dev="aider --model $AIDER_MODEL --weak-model $AIDER_WEAK_MODEL"

# Claude Code
export CLAUDE_CODE_MAX_TURNS="${CLAUDE_CODE_MAX_TURNS:-50}"

# Cursor
alias cursor-agent="cursor --agent"

# Continue
alias continue-dev="continue --model deepseek-coder"

# Git worktrees for AI agents
ai-worktree() {
  local branch=$1
  local repo_root=$(git rev-parse --show-toplevel 2>/dev/null)
  if [[ -n "$repo_root" && -n "$branch" ]]; then
    local wt_path="$repo_root/../$(basename $repo_root)-$branch"
    git worktree add "$wt_path" "$branch" 2>/dev/null || git worktree add "$wt_path" -b "$branch"
    cd "$wt_path"
  fi
}
```

### 310-hermes.zsh (Hermes Integration)

```zsh
# Hermes Integration
# Only loaded when .features.ai.hermes.dashboard.enabled = true

export HERMES_URL="${HERMES_URL:-http://localhost:9119}"
export HERMES_API_KEY="${HERMES_API_KEY:-}"

# Hermes CLI aliases
alias hm="hermes"
alias hm-chat="hermes chat"
alias hm-task="hermes task"
alias hm-status="hermes status"
alias hm-logs="hermes logs"

# Hermes sync (backup)
hm-sync() {
  if command -v hermes-sync &>/dev/null; then
    hermes-sync backup --output "$HOME/.local/share/hermes/backups/$(date +%Y%m%d).sql"
  fi
}
```

### 999-compinit.zsh (LAST - Completion Initialization)

```zsh
# Compinit - MUST BE LAST
# Load completion system
autoload -Uz compinit
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"

# Rebuild completion cache daily
if [[ -n "$ZSH_COMPDUMP" && ! -f "$ZSH_COMPDUMP" ]]; then
  compinit -d "$ZSH_COMPDUMP"
fi

# Completion styling
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''

# FZF-tab integration
zstyle ':fzf-tab:*' fzf-flags --height=50% --reverse
zstyle ':fzf-tab:complete:*' fzf-preview 'bat --color=always --style=numbers --line-range=:500 $realpath'
```

---

## 4. Encrypted Secrets Loading Pattern

### In Template (Auto-decrypt on Source)

```go
{{- if .features.secrets.gpg }}
{{- $secrets := list
  "encrypted_api_keys.zsh.asc"
  "encrypted_ssh_config.zsh.asc"
  "encrypted_workplace.zsh.asc"
-}}
{{- range $secrets }}
# {{ . }} - GPG encrypted secrets
if [[ -f "{{ .chezmoi.homeDir }}/.config/{{ . }}" ]]; then
  source <(gpg --quiet --decrypt "{{ .chezmoi.homeDir }}/.config/{{ . }}" 2>/dev/null) || {
    print -P "%F{red}Failed to decrypt {{ . }}%f" >&2
  }
fi
{{- end }}
{{- end }}
```

### Manual Decrypt (for debugging)

```bash
# Decrypt to stdout
gpg --decrypt ~/.config/encrypted_api_keys.zsh.asc

# Decrypt to file
gpg --output ~/.config/api_keys.zsh --decrypt ~/.config/encrypted_api_keys.zsh.asc

# Test if gpg-agent is running
gpg-connect-agent /bye
```

---

## 5. Adding a New Module

### 1. Create Module File

```zsh
# home/dot_zshrc.d/185-new-tool.zsh
# Description: New tool integration

# Only load if tool exists
if command -v newtool &>/dev/null; then
  export NEWTOOL_CONFIG="$HOME/.config/newtool"
  alias nt="newtool"
  
  # Completions
  if [[ -f "$HOME/.local/share/zsh/site-functions/_newtool" ]]; then
    fpath=("$HOME/.local/share/zsh/site-functions" $fpath)
  fi
fi
```

### 2. Add to Main Template

```go
# In dot_zshrc.tmpl, after 180-tools.zsh
source "{{ .chezmoi.homeDir }}/.zshrc.d/185-new-tool.zsh"
```

### 3. Numbering Convention

| Range | Purpose |
|-------|---------|
| 000-099 | Environment (must be first) |
| 100-199 | Core shell (zinit, plugins, basics) |
| 200-299 | Profile-specific (work, personal, vps) |
| 300-399 | Feature-specific (AI, monitoring, etc.) |
| 400-499 | Application-specific |
| 900-999 | Finalization (compinit, prompt) |

---

## 6. Testing Zsh Config

### Dry Run (Syntax Check)

```bash
# Test template rendering
chezmoi execute-template home/dot_zshrc.tmpl > /tmp/test.zshrc
zsh -n /tmp/test.zshrc  # Syntax check only

# Test with profile data
chezmoi execute-template --data='{"settings":{"profile":"vps"}}' home/dot_zshrc.tmpl | zsh -n
```

### Module Load Test

```bash
#!/usr/bin/env zsh
# test_zsh_modules.zsh

for module in ~/.zshrc.d/*.zsh(N); do
  echo "Testing $module..."
  zsh -c "source $module" 2>&1 | head -5
  if [[ $? -eq 0 ]]; then
    echo "  ✅ OK"
  else
    echo "  ❌ FAILED"
  fi
done
```

---

## 7. Common Issues & Fixes

| Issue | Cause | Fix |
|-------|-------|-----|
| `command not found` in module | Module loads before PATH set | Move to 099-environment.zsh or later |
| Compinit errors | Duplicate compinit calls | Ensure only 999-compinit.zsh calls compinit |
| Starship not showing | Starship init before compinit | Move `eval "$(starship init zsh)"` after compinit |
| GPG decrypt fails | gpg-agent not running | `gpg-connect-agent /bye` or `export GPG_TTY=$(tty)` |
| Zinit plugins not loading | Zinit not sourced first | Ensure 100-zinit.zsh sourced before 120-plugins.zsh |
| Work config on personal | Workplace detection wrong | Check `.chezmoi.yaml.tmpl` detection logic |

---

## 8. Related Skills

| Skill | Relationship |
|-------|--------------|
| `chezmoi-architecture` | Prerequisite: understands template system |
| `chezmoi-template-patterns` | Main template uses Go templates |
| `chezmoi-multi-profile` | Conditional module loading per profile |
| `chezmoi-secret-management` | GPG-encrypted secrets loading |
| `chezmoi-ignore-patterns` | Exclude modules per profile |
| `dotfiles-workplace-zup` | Work profile module details |

---

## 9. References

- **Repo Zsh**: `fabiosouzadev/dotfiles` → `home/dot_zshrc.tmpl`, `home/dot_zshrc.d/`
- **Zinit docs**: https://zdharma-continuum.github.io/zinit/
- **Starship docs**: https://starship.rs/
- **Atuin docs**: https://atuin.sh/
- **Mise docs**: https://mise.jdx.dev/

---

*Generated via Loop Engineering Mode — Phase 4: Skill Creation. Validated against live repo analysis.*