[dell3520]
enabled = false

[rtl8821ce]
enabled = false

[dell3530]
enabled = false

[kernels]
install = true

[ollama]
compiled = true
localmodels = false

[openclaw]
install = false

[i3]
install = false

[niri]
install = true
