# Pattern Catalog: fabiosouzadev/dotfiles

Extracted during Loop Engineering analysis (2026-08-03). Each pattern labeled FACT (direct evidence) or INFERENCE (reasoned).

---

## Structural Patterns

| Pattern | Location | Label | Notes |
|---------|----------|-------|-------|
| Source dir = `home/` | `.chezmoiroot` contains `home` | FACT | Non-standard (default is `.`) |
| Config template = `.chezmoi.yaml.tmpl` | Root of source dir | FACT | Generates `~/.config/chezmoi/chezmoi.yaml` |
| Ignore template = `.chezmoiignore.tmpl` | Root of source dir | FACT | Conditional by `.settings` |
| Data dir = `.chezmoidata/` | `home/.chezmoidata/` | FACT | Per-OS + global YAML |
| Scripts dir = `.chezmoiscripts/` | `home/.chezmoiscripts/` | FACT | Per-OS + `unix/` + `vps/` |
| Templates dir = `.chezmoitemplates/` | `home/.chezmoitemplates/` | FACT | `common/` + OS + `workplace/` |
| Zsh modules dir = `dot_zshrc.d/` | `home/dot_zshrc.d/` | FACT | Numbered 099-999, sourced in order |
| Encrypted configs prefix = `private_` | `home/private_dot_*/` | FACT | Decrypted via age on apply |
| GPG secrets = `encrypted_*.asc` | `home/encrypted_*.zsh.asc` | FACT | Sourced in Zsh modules |
| Docs dir = `docs/` | Root | FACT | Generated by `gsd-doc-writer` |
| Planning dir = `.planning/` | Root | FACT | GSD methodology artifacts |

---

## Naming Convention Patterns

| Pattern | Example | Label | Notes |
|---------|---------|-------|-------|
| Lifecycle scripts: `run_once_before_XXX` | `run_once_before_216-install-wm.sh.tmpl` | FACT | Pre-install, ordered by number |
| Lifecycle scripts: `run_once_after_XXX` | `run_once_after_590-install-ai-tools.sh.tmpl` | FACT | Post-install, ordered by number |
| Lifecycle scripts: `run_onchange_after_XXX` | `run_onchange_after_605-clone-my-repos.sh.tmpl` | FACT | Re-runnable on template change |
| Template guards: `script_is_not_*` | `script_is_not_ephemeral`, `script_is_not_headless` | FACT | Exit 0 if condition met |
| Feature flags: `features.<domain>.<feature>` | `features.ai.hermes.dashboard.enabled` | FACT | Hierarchical, ternary defaults |
| Profile detection: `$profile` variable | `personal` \| `work` \| `vps` | FACT | Set in `.chezmoi.yaml.tmpl` |
| Environment flags: `$ephemeral`, `$headless`, `$guiAvailable` | Set in `.chezmoi.yaml.tmpl` | FACT | Control script execution |
| Workspace bases: `BASE_PERSONAL`, `BASE_WORK`, `BASE_OTHER` | Clone script variables | FACT | `~/Workspaces/{Personal,Work,Others}` |

---

## Template Patterns

| Pattern | Example | Label | Notes |
|---------|---------|-------|-------|
| Guard template inclusion | `{{ template "common/script_is_not_ephemeral" . }}` | FACT | At top of lifecycle scripts |
| Helper template inclusion | `{{ template "common/script_helper" . }}` | FACT | Provides `info/warn/error/success` |
| Mise eval template | `{{ template "common/script_eval_mise" . }}` | FACT | Activates mise in bash |
| Conditional ignore | `{{ if .settings.vps }} ... {{ end }}` | FACT | In `.chezmoiignore.tmpl` |
| Feature flag gating | `{{ if .features.ai.hermes.dashboard.enabled }}` | FACT | In scripts and templates |
| Ternary for complex logic | `{{ ternary true false condition }}` | FACT | Used for `$guiAvailable` |
| Range loops over data | `{{ range .ai_tools.npm }}` | FACT | In `run_once_after_590-install-ai-tools.sh.tmpl` |
| Data consolidation | `data: {{ $data \| toYaml \| indent 2 }}` | FACT | At end of `.chezmoi.yaml.tmpl` |

---

## Script Patterns

| Pattern | Example | Label | Notes |
|---------|---------|-------|-------|
| Idempotent install check | `if ! command -v "tool" > /dev/null; then install; fi` | FACT | In universal binary scripts |
| OS-specific package install | `if eq .chezmoi.os "linux" ...` | FACT | In clone script for git/jq |
| Feature flag + block check | `$featureEnabled` + `$blocked` variables | FACT | In AI tools install script |
| Completion generation | `completions_cmd > ~/.local/share/zsh/site-functions/_tool` | FACT | For npm tools with `completions_cmd` |
| Workspace mkdir before clone | `mkdir -p "$BASE_PERSONAL"` | FACT | In clone script |
| Workplace-specific clone | `if eq $workplaceName "Zup"` | FACT | Only for work profile + Zup workplace |

---

## Secret Management Patterns

| Pattern | Example | Label | Notes |
|---------|---------|-------|-------|
| age encryption for chezmoi | `private_dot_config/`, `private_dot_hermes/` | FACT | Recipient hardcoded in template |
| GPG encryption for shell | `encrypted_300-ai-api-keys.zsh.asc` | FACT | Sourced in Zsh module |
| Dual system coexistence | Both age and GPG used | FACT | Different use cases |
| Recipient in template | `recipient: E691C031009FB1DAA3A25125212D516F623C5747` | FACT | Hardcoded in `.chezmoi.yaml.tmpl` |
| Selective sync for Hermes | `hermes-sync-push/pull` exports manifest + SQL | FACT | Not full DB backup |
| Selective sync for OmniRoute | `omniroute-sync-push/pull` exports config SQL | FACT | Not full DB backup |

---

## AI Integration Patterns

| Pattern | Example | Label | Notes |
|---------|---------|-------|-------|
| Feature-flagged install | `features.ai.coding_orchestrator.install` | FACT | Controls entire stack |
| Budget-controlled execution | `nightly_budget_usd: 5`, `per_task_budget_usd: 2` | FACT | In `.chezmoi.yaml.tmpl` |
| Worktree isolation | `~/worktrees/task-<id>` | FACT | Per-task Git worktree |
| Multi-agent support | Aider, Claude Code, Codex, Gemini, OpenCode | FACT | Configurable via skill |
| Trigger diversity | GitHub label, Telegram, webhook, cron | FACT | Coding Orchestrator triggers |
| Context gathering pipeline | GitHub API, Git diff, Notion MCP, mem0, repo files | FACT | Before agent execution |
| Delivery channels | Telegram, Notion, GitHub PR comments | FACT | Configurable |

---

## VPS-Specific Patterns

| Pattern | Example | Label | Notes |
|---------|---------|-------|-------|
| Auto-detection heuristics | `instance-*` hostname, `ubuntu` user, SSH, no GUI | FACT | Sets `$isVps = true` |
| Feature override for VPS | `features.ai.ollama.install = not $isVps` | FACT | Disables Ollama on VPS |
| Conditional ignore for VPS | `.chezmoiignore.tmpl` blocks desktop scripts | FACT | WM, fonts, drivers, VPN, etc. |
| VPS-only scripts | `.chezmoiscripts/vps/` directory | FACT | Dockge, Caddy, AgentMemory, Camofox |
| Subdomain-based access | `hermes.fabiosouzadev.duckdns.org` | FACT | Caddy reverse proxy |
| Tailscale for VPN | `features.tailscale.enabled: true` | FACT | Replaces OpenVPN/Instivo |

---

## Philosophical / Inferred Patterns

| Pattern | Evidence | Label | Notes |
|---------|----------|-------|-------|
| Reproducibility > convenience | README, ARCHITECTURE.md | INFERENCE | Bootstrap in 1 command, auto-detection |
| IA as first-class citizen | AI tools in bootstrap, dedicated scripts | INFERENCE | Hermes, OmniRoute, Coding Orchestrator |
| Universal binary over package manager | ARCHITECTURE.md section | INFERENCE | For tools not in apt, no sudo, cross-platform |
| Zinit preferred over Oh My Zsh | Only Zinit found in repo | INFERENCE | Could be historical |
| Aider as default coding agent | README "Aider (padrão, via OmniRoute)" | INFERENCE | Others configurable |
| Worktree isolation for coding | README "Worktree Isolation" | INFERENCE | Git worktrees per task |
| Selective backup over full | HERMES-BACKUP.md, OMNIROUTE-BACKUP.md | INFERENCE | "Not history, identity/config" |
| Modular over monolithic | dot_zshrc.d, separate data/scripts/templates | INFERENCE | Clear separation of concerns |
| Idempotency mandatory | All scripts check before install | INFERENCE | Re-runnable safely |
| Security by default | age + GPG, private_ prefix, encrypted_ prefix | INFERENCE | No plaintext secrets in Git |

---

## Anti-Patterns (Things NOT Done)

| Anti-Pattern | Evidence | Label |
|--------------|----------|-------|
| No monolithic backup tarballs | HERMES-BACKUP.md explicitly forbids | FACT |
| No unencrypted secrets in Git | All secrets via age/GPG | FACT |
| No hardcoded paths (mostly) | Uses `.chezmoi.homeDir`, `joinPath` | FACT |
| No manual steps in bootstrap | Everything in scripts/templates | FACT |
| No untracked runtime state in repo | Logs, caches, DBs excluded | FACT |
| No single-profile assumption | personal/work/vps all supported | FACT |