# -*-mode:toml-*- vim:ft=toml

[packages.homebrew]

tap = [
    'homebrew/core',
    'homebrew/cask',
    'homebrew/bundle',
    'homebrew/cask-fonts',
    'homebrew/cask-versions',
    'nicoverbruggen/homebrew-cask',
    'ferdium/ferdium'
]

brew = [
    'lazyjournal',
]

cask = [
    # App
    'ente-auth',
    'bitwarden',
    'macs-fan-control',
    'spotify',
    'appcleaner',
    'microsoft-teams',
    'notion',
    'dbeaver-community',
    'transmission',
    'vlc',
    #'stack-stack',
    'keepingyouawake',
    'appcleaner',
    'figma',
    'rectangle',
    'zoom',
    'signal',
    'drawio',
    'obsidian',
    'localsend',
    'streamlink-twitch-gui',
    'raycast',

    # terminal
    'kitty',
    'wezterm',
    
    # Ide
    'antigravity',
    'intellij-idea-ce',
    'visual-studio-code',
    'visual-studio-code@insiders',
    'vscodium',
    'vscodium@insiders',
    'cursor',

    # BROWSERS    
    'chromium',
    'brave-browser@nightly',
    'google-chrome@beta',
    'firefox@beta',

    # environment
    'github@beta',
    'podman-desktop',
    'openlens',
    'devpod'
]

[[packages.homebrew.mas]]
name = "The Unarchiver"
id   = 425424353

[[packages.homebrew.mas]]
name = "Battery Health"
id   = 490192174

[[packages.homebrew.mas]]
name = "ColorSlurp"
id   = 1287239339

[[packages.homebrew.mas]]
name = "Memory Diag"
id   = 748212890

[[packages.homebrew.mas]]
name = "Speedtest"
id   = 1153157709

[[packages.homebrew.mas]]
name = "Xcode"
id   = 497799835


[packages]
macports = [
    'eza',
    'gnupg2',
    'lazygit',
    'neofetch',
    'direnv',
    'ranger',
    'duf',
    'bat',
    'git-delta',
    'hey', # Like a ab (ApacheBench)
    'yazi',
    'fd',
    'zoxide',
    'age',
    'starship',
    # 'fzf',
    'jq',
    'tree',
    'wget',
    'htop',
    'btop',
    'podman',   
    'podman-compose',
    'lima',
    'colima',
    'k9s',
    'grep'
]